package com.worldpara.domain;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class BookInventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_inventory.bookitem_id
     *
     * @mbg.generated
     */
    private Integer bookitemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_inventory.library_id
     *
     * @mbg.generated
     */
    private Integer libraryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_inventory.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_inventory.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_inventory.in_date
     *
     * @mbg.generated
     */
    private Date inDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_inventory.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_inventory.bookitem_id
     *
     * @return the value of book_inventory.bookitem_id
     *
     * @mbg.generated
     */
    public Integer getBookitemId() {
        return bookitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_inventory.bookitem_id
     *
     * @param bookitemId the value for book_inventory.bookitem_id
     *
     * @mbg.generated
     */
    public void setBookitemId(Integer bookitemId) {
        this.bookitemId = bookitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_inventory.library_id
     *
     * @return the value of book_inventory.library_id
     *
     * @mbg.generated
     */
    public Integer getLibraryId() {
        return libraryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_inventory.library_id
     *
     * @param libraryId the value for book_inventory.library_id
     *
     * @mbg.generated
     */
    public void setLibraryId(Integer libraryId) {
        this.libraryId = libraryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_inventory.book_id
     *
     * @return the value of book_inventory.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_inventory.book_id
     *
     * @param bookId the value for book_inventory.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_inventory.status
     *
     * @return the value of book_inventory.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_inventory.status
     *
     * @param status the value for book_inventory.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_inventory.in_date
     *
     * @return the value of book_inventory.in_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    public Date getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_inventory.in_date
     *
     * @param inDate the value for book_inventory.in_date
     *
     * @mbg.generated
     */
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_inventory.location
     *
     * @return the value of book_inventory.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_inventory.location
     *
     * @param location the value for book_inventory.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}