package com.worldpara.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BorrowRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    public BorrowRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBorrowIdIsNull() {
            addCriterion("borrow_id is null");
            return (Criteria) this;
        }

        public Criteria andBorrowIdIsNotNull() {
            addCriterion("borrow_id is not null");
            return (Criteria) this;
        }

        public Criteria andBorrowIdEqualTo(Integer value) {
            addCriterion("borrow_id =", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdNotEqualTo(Integer value) {
            addCriterion("borrow_id <>", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdGreaterThan(Integer value) {
            addCriterion("borrow_id >", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("borrow_id >=", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdLessThan(Integer value) {
            addCriterion("borrow_id <", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdLessThanOrEqualTo(Integer value) {
            addCriterion("borrow_id <=", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdIn(List<Integer> values) {
            addCriterion("borrow_id in", values, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdNotIn(List<Integer> values) {
            addCriterion("borrow_id not in", values, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdBetween(Integer value1, Integer value2) {
            addCriterion("borrow_id between", value1, value2, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdNotBetween(Integer value1, Integer value2) {
            addCriterion("borrow_id not between", value1, value2, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNull() {
            addCriterion("book_id is null");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNotNull() {
            addCriterion("book_id is not null");
            return (Criteria) this;
        }

        public Criteria andBookIdEqualTo(Integer value) {
            addCriterion("book_id =", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotEqualTo(Integer value) {
            addCriterion("book_id <>", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThan(Integer value) {
            addCriterion("book_id >", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("book_id >=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThan(Integer value) {
            addCriterion("book_id <", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThanOrEqualTo(Integer value) {
            addCriterion("book_id <=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdIn(List<Integer> values) {
            addCriterion("book_id in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotIn(List<Integer> values) {
            addCriterion("book_id not in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdBetween(Integer value1, Integer value2) {
            addCriterion("book_id between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotBetween(Integer value1, Integer value2) {
            addCriterion("book_id not between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookitemIdIsNull() {
            addCriterion("bookitem_id is null");
            return (Criteria) this;
        }

        public Criteria andBookitemIdIsNotNull() {
            addCriterion("bookitem_id is not null");
            return (Criteria) this;
        }

        public Criteria andBookitemIdEqualTo(Integer value) {
            addCriterion("bookitem_id =", value, "bookitemId");
            return (Criteria) this;
        }

        public Criteria andBookitemIdNotEqualTo(Integer value) {
            addCriterion("bookitem_id <>", value, "bookitemId");
            return (Criteria) this;
        }

        public Criteria andBookitemIdGreaterThan(Integer value) {
            addCriterion("bookitem_id >", value, "bookitemId");
            return (Criteria) this;
        }

        public Criteria andBookitemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bookitem_id >=", value, "bookitemId");
            return (Criteria) this;
        }

        public Criteria andBookitemIdLessThan(Integer value) {
            addCriterion("bookitem_id <", value, "bookitemId");
            return (Criteria) this;
        }

        public Criteria andBookitemIdLessThanOrEqualTo(Integer value) {
            addCriterion("bookitem_id <=", value, "bookitemId");
            return (Criteria) this;
        }

        public Criteria andBookitemIdIn(List<Integer> values) {
            addCriterion("bookitem_id in", values, "bookitemId");
            return (Criteria) this;
        }

        public Criteria andBookitemIdNotIn(List<Integer> values) {
            addCriterion("bookitem_id not in", values, "bookitemId");
            return (Criteria) this;
        }

        public Criteria andBookitemIdBetween(Integer value1, Integer value2) {
            addCriterion("bookitem_id between", value1, value2, "bookitemId");
            return (Criteria) this;
        }

        public Criteria andBookitemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bookitem_id not between", value1, value2, "bookitemId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOutuserIdIsNull() {
            addCriterion("outuser_id is null");
            return (Criteria) this;
        }

        public Criteria andOutuserIdIsNotNull() {
            addCriterion("outuser_id is not null");
            return (Criteria) this;
        }

        public Criteria andOutuserIdEqualTo(Integer value) {
            addCriterion("outuser_id =", value, "outuserId");
            return (Criteria) this;
        }

        public Criteria andOutuserIdNotEqualTo(Integer value) {
            addCriterion("outuser_id <>", value, "outuserId");
            return (Criteria) this;
        }

        public Criteria andOutuserIdGreaterThan(Integer value) {
            addCriterion("outuser_id >", value, "outuserId");
            return (Criteria) this;
        }

        public Criteria andOutuserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("outuser_id >=", value, "outuserId");
            return (Criteria) this;
        }

        public Criteria andOutuserIdLessThan(Integer value) {
            addCriterion("outuser_id <", value, "outuserId");
            return (Criteria) this;
        }

        public Criteria andOutuserIdLessThanOrEqualTo(Integer value) {
            addCriterion("outuser_id <=", value, "outuserId");
            return (Criteria) this;
        }

        public Criteria andOutuserIdIn(List<Integer> values) {
            addCriterion("outuser_id in", values, "outuserId");
            return (Criteria) this;
        }

        public Criteria andOutuserIdNotIn(List<Integer> values) {
            addCriterion("outuser_id not in", values, "outuserId");
            return (Criteria) this;
        }

        public Criteria andOutuserIdBetween(Integer value1, Integer value2) {
            addCriterion("outuser_id between", value1, value2, "outuserId");
            return (Criteria) this;
        }

        public Criteria andOutuserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("outuser_id not between", value1, value2, "outuserId");
            return (Criteria) this;
        }

        public Criteria andOutDateIsNull() {
            addCriterion("out_date is null");
            return (Criteria) this;
        }

        public Criteria andOutDateIsNotNull() {
            addCriterion("out_date is not null");
            return (Criteria) this;
        }

        public Criteria andOutDateEqualTo(Date value) {
            addCriterion("out_date =", value, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateNotEqualTo(Date value) {
            addCriterion("out_date <>", value, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateGreaterThan(Date value) {
            addCriterion("out_date >", value, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateGreaterThanOrEqualTo(Date value) {
            addCriterion("out_date >=", value, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateLessThan(Date value) {
            addCriterion("out_date <", value, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateLessThanOrEqualTo(Date value) {
            addCriterion("out_date <=", value, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateIn(List<Date> values) {
            addCriterion("out_date in", values, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateNotIn(List<Date> values) {
            addCriterion("out_date not in", values, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateBetween(Date value1, Date value2) {
            addCriterion("out_date between", value1, value2, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateNotBetween(Date value1, Date value2) {
            addCriterion("out_date not between", value1, value2, "outDate");
            return (Criteria) this;
        }

        public Criteria andBackDateIsNull() {
            addCriterion("back_date is null");
            return (Criteria) this;
        }

        public Criteria andBackDateIsNotNull() {
            addCriterion("back_date is not null");
            return (Criteria) this;
        }

        public Criteria andBackDateEqualTo(Date value) {
            addCriterion("back_date =", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateNotEqualTo(Date value) {
            addCriterion("back_date <>", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateGreaterThan(Date value) {
            addCriterion("back_date >", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateGreaterThanOrEqualTo(Date value) {
            addCriterion("back_date >=", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateLessThan(Date value) {
            addCriterion("back_date <", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateLessThanOrEqualTo(Date value) {
            addCriterion("back_date <=", value, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateIn(List<Date> values) {
            addCriterion("back_date in", values, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateNotIn(List<Date> values) {
            addCriterion("back_date not in", values, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateBetween(Date value1, Date value2) {
            addCriterion("back_date between", value1, value2, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackDateNotBetween(Date value1, Date value2) {
            addCriterion("back_date not between", value1, value2, "backDate");
            return (Criteria) this;
        }

        public Criteria andBackuserIdIsNull() {
            addCriterion("backuser_id is null");
            return (Criteria) this;
        }

        public Criteria andBackuserIdIsNotNull() {
            addCriterion("backuser_id is not null");
            return (Criteria) this;
        }

        public Criteria andBackuserIdEqualTo(Integer value) {
            addCriterion("backuser_id =", value, "backuserId");
            return (Criteria) this;
        }

        public Criteria andBackuserIdNotEqualTo(Integer value) {
            addCriterion("backuser_id <>", value, "backuserId");
            return (Criteria) this;
        }

        public Criteria andBackuserIdGreaterThan(Integer value) {
            addCriterion("backuser_id >", value, "backuserId");
            return (Criteria) this;
        }

        public Criteria andBackuserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("backuser_id >=", value, "backuserId");
            return (Criteria) this;
        }

        public Criteria andBackuserIdLessThan(Integer value) {
            addCriterion("backuser_id <", value, "backuserId");
            return (Criteria) this;
        }

        public Criteria andBackuserIdLessThanOrEqualTo(Integer value) {
            addCriterion("backuser_id <=", value, "backuserId");
            return (Criteria) this;
        }

        public Criteria andBackuserIdIn(List<Integer> values) {
            addCriterion("backuser_id in", values, "backuserId");
            return (Criteria) this;
        }

        public Criteria andBackuserIdNotIn(List<Integer> values) {
            addCriterion("backuser_id not in", values, "backuserId");
            return (Criteria) this;
        }

        public Criteria andBackuserIdBetween(Integer value1, Integer value2) {
            addCriterion("backuser_id between", value1, value2, "backuserId");
            return (Criteria) this;
        }

        public Criteria andBackuserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("backuser_id not between", value1, value2, "backuserId");
            return (Criteria) this;
        }

        public Criteria andActualBackDateIsNull() {
            addCriterion("actual_back_date is null");
            return (Criteria) this;
        }

        public Criteria andActualBackDateIsNotNull() {
            addCriterion("actual_back_date is not null");
            return (Criteria) this;
        }

        public Criteria andActualBackDateEqualTo(Date value) {
            addCriterion("actual_back_date =", value, "actualBackDate");
            return (Criteria) this;
        }

        public Criteria andActualBackDateNotEqualTo(Date value) {
            addCriterion("actual_back_date <>", value, "actualBackDate");
            return (Criteria) this;
        }

        public Criteria andActualBackDateGreaterThan(Date value) {
            addCriterion("actual_back_date >", value, "actualBackDate");
            return (Criteria) this;
        }

        public Criteria andActualBackDateGreaterThanOrEqualTo(Date value) {
            addCriterion("actual_back_date >=", value, "actualBackDate");
            return (Criteria) this;
        }

        public Criteria andActualBackDateLessThan(Date value) {
            addCriterion("actual_back_date <", value, "actualBackDate");
            return (Criteria) this;
        }

        public Criteria andActualBackDateLessThanOrEqualTo(Date value) {
            addCriterion("actual_back_date <=", value, "actualBackDate");
            return (Criteria) this;
        }

        public Criteria andActualBackDateIn(List<Date> values) {
            addCriterion("actual_back_date in", values, "actualBackDate");
            return (Criteria) this;
        }

        public Criteria andActualBackDateNotIn(List<Date> values) {
            addCriterion("actual_back_date not in", values, "actualBackDate");
            return (Criteria) this;
        }

        public Criteria andActualBackDateBetween(Date value1, Date value2) {
            addCriterion("actual_back_date between", value1, value2, "actualBackDate");
            return (Criteria) this;
        }

        public Criteria andActualBackDateNotBetween(Date value1, Date value2) {
            addCriterion("actual_back_date not between", value1, value2, "actualBackDate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andWhetherExtIsNull() {
            addCriterion("whether_ext is null");
            return (Criteria) this;
        }

        public Criteria andWhetherExtIsNotNull() {
            addCriterion("whether_ext is not null");
            return (Criteria) this;
        }

        public Criteria andWhetherExtEqualTo(String value) {
            addCriterion("whether_ext =", value, "whetherExt");
            return (Criteria) this;
        }

        public Criteria andWhetherExtNotEqualTo(String value) {
            addCriterion("whether_ext <>", value, "whetherExt");
            return (Criteria) this;
        }

        public Criteria andWhetherExtGreaterThan(String value) {
            addCriterion("whether_ext >", value, "whetherExt");
            return (Criteria) this;
        }

        public Criteria andWhetherExtGreaterThanOrEqualTo(String value) {
            addCriterion("whether_ext >=", value, "whetherExt");
            return (Criteria) this;
        }

        public Criteria andWhetherExtLessThan(String value) {
            addCriterion("whether_ext <", value, "whetherExt");
            return (Criteria) this;
        }

        public Criteria andWhetherExtLessThanOrEqualTo(String value) {
            addCriterion("whether_ext <=", value, "whetherExt");
            return (Criteria) this;
        }

        public Criteria andWhetherExtLike(String value) {
            addCriterion("whether_ext like", value, "whetherExt");
            return (Criteria) this;
        }

        public Criteria andWhetherExtNotLike(String value) {
            addCriterion("whether_ext not like", value, "whetherExt");
            return (Criteria) this;
        }

        public Criteria andWhetherExtIn(List<String> values) {
            addCriterion("whether_ext in", values, "whetherExt");
            return (Criteria) this;
        }

        public Criteria andWhetherExtNotIn(List<String> values) {
            addCriterion("whether_ext not in", values, "whetherExt");
            return (Criteria) this;
        }

        public Criteria andWhetherExtBetween(String value1, String value2) {
            addCriterion("whether_ext between", value1, value2, "whetherExt");
            return (Criteria) this;
        }

        public Criteria andWhetherExtNotBetween(String value1, String value2) {
            addCriterion("whether_ext not between", value1, value2, "whetherExt");
            return (Criteria) this;
        }

        public Criteria andPrevBorrowIdIsNull() {
            addCriterion("prev_borrow_id is null");
            return (Criteria) this;
        }

        public Criteria andPrevBorrowIdIsNotNull() {
            addCriterion("prev_borrow_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrevBorrowIdEqualTo(Integer value) {
            addCriterion("prev_borrow_id =", value, "prevBorrowId");
            return (Criteria) this;
        }

        public Criteria andPrevBorrowIdNotEqualTo(Integer value) {
            addCriterion("prev_borrow_id <>", value, "prevBorrowId");
            return (Criteria) this;
        }

        public Criteria andPrevBorrowIdGreaterThan(Integer value) {
            addCriterion("prev_borrow_id >", value, "prevBorrowId");
            return (Criteria) this;
        }

        public Criteria andPrevBorrowIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("prev_borrow_id >=", value, "prevBorrowId");
            return (Criteria) this;
        }

        public Criteria andPrevBorrowIdLessThan(Integer value) {
            addCriterion("prev_borrow_id <", value, "prevBorrowId");
            return (Criteria) this;
        }

        public Criteria andPrevBorrowIdLessThanOrEqualTo(Integer value) {
            addCriterion("prev_borrow_id <=", value, "prevBorrowId");
            return (Criteria) this;
        }

        public Criteria andPrevBorrowIdIn(List<Integer> values) {
            addCriterion("prev_borrow_id in", values, "prevBorrowId");
            return (Criteria) this;
        }

        public Criteria andPrevBorrowIdNotIn(List<Integer> values) {
            addCriterion("prev_borrow_id not in", values, "prevBorrowId");
            return (Criteria) this;
        }

        public Criteria andPrevBorrowIdBetween(Integer value1, Integer value2) {
            addCriterion("prev_borrow_id between", value1, value2, "prevBorrowId");
            return (Criteria) this;
        }

        public Criteria andPrevBorrowIdNotBetween(Integer value1, Integer value2) {
            addCriterion("prev_borrow_id not between", value1, value2, "prevBorrowId");
            return (Criteria) this;
        }

        public Criteria andExtDateIsNull() {
            addCriterion("ext_date is null");
            return (Criteria) this;
        }

        public Criteria andExtDateIsNotNull() {
            addCriterion("ext_date is not null");
            return (Criteria) this;
        }

        public Criteria andExtDateEqualTo(Date value) {
            addCriterion("ext_date =", value, "extDate");
            return (Criteria) this;
        }

        public Criteria andExtDateNotEqualTo(Date value) {
            addCriterion("ext_date <>", value, "extDate");
            return (Criteria) this;
        }

        public Criteria andExtDateGreaterThan(Date value) {
            addCriterion("ext_date >", value, "extDate");
            return (Criteria) this;
        }

        public Criteria andExtDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ext_date >=", value, "extDate");
            return (Criteria) this;
        }

        public Criteria andExtDateLessThan(Date value) {
            addCriterion("ext_date <", value, "extDate");
            return (Criteria) this;
        }

        public Criteria andExtDateLessThanOrEqualTo(Date value) {
            addCriterion("ext_date <=", value, "extDate");
            return (Criteria) this;
        }

        public Criteria andExtDateIn(List<Date> values) {
            addCriterion("ext_date in", values, "extDate");
            return (Criteria) this;
        }

        public Criteria andExtDateNotIn(List<Date> values) {
            addCriterion("ext_date not in", values, "extDate");
            return (Criteria) this;
        }

        public Criteria andExtDateBetween(Date value1, Date value2) {
            addCriterion("ext_date between", value1, value2, "extDate");
            return (Criteria) this;
        }

        public Criteria andExtDateNotBetween(Date value1, Date value2) {
            addCriterion("ext_date not between", value1, value2, "extDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_record
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_record
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}