package com.worldpara.domain;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class BorrowRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.borrow_id
     *
     * @mbg.generated
     */
    private Integer borrowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.bookitem_id
     *
     * @mbg.generated
     */
    private Integer bookitemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.outuser_id
     *
     * @mbg.generated
     */
    private Integer outuserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.out_date
     *
     * @mbg.generated
     */
    private Date outDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.back_date
     *
     * @mbg.generated
     */
    private Date backDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.backuser_id
     *
     * @mbg.generated
     */
    private Integer backuserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.actual_back_date
     *
     * @mbg.generated
     */
    private Date actualBackDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.whether_ext
     *
     * @mbg.generated
     */
    private String whetherExt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.prev_borrow_id
     *
     * @mbg.generated
     */
    private Integer prevBorrowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_record.ext_date
     *
     * @mbg.generated
     */
    private Date extDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.borrow_id
     *
     * @return the value of borrow_record.borrow_id
     *
     * @mbg.generated
     */
    public Integer getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.borrow_id
     *
     * @param borrowId the value for borrow_record.borrow_id
     *
     * @mbg.generated
     */
    public void setBorrowId(Integer borrowId) {
        this.borrowId = borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.book_id
     *
     * @return the value of borrow_record.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.book_id
     *
     * @param bookId the value for borrow_record.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.bookitem_id
     *
     * @return the value of borrow_record.bookitem_id
     *
     * @mbg.generated
     */
    public Integer getBookitemId() {
        return bookitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.bookitem_id
     *
     * @param bookitemId the value for borrow_record.bookitem_id
     *
     * @mbg.generated
     */
    public void setBookitemId(Integer bookitemId) {
        this.bookitemId = bookitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.user_id
     *
     * @return the value of borrow_record.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.user_id
     *
     * @param userId the value for borrow_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.outuser_id
     *
     * @return the value of borrow_record.outuser_id
     *
     * @mbg.generated
     */
    public Integer getOutuserId() {
        return outuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.outuser_id
     *
     * @param outuserId the value for borrow_record.outuser_id
     *
     * @mbg.generated
     */
    public void setOutuserId(Integer outuserId) {
        this.outuserId = outuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.out_date
     *
     * @return the value of borrow_record.out_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    public Date getOutDate() {
        return outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.out_date
     *
     * @param outDate the value for borrow_record.out_date
     *
     * @mbg.generated
     */
    public void setOutDate(Date outDate) {
        this.outDate = outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.back_date
     *
     * @return the value of borrow_record.back_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    public Date getBackDate() {
        return backDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.back_date
     *
     * @param backDate the value for borrow_record.back_date
     *
     * @mbg.generated
     */
    public void setBackDate(Date backDate) {
        this.backDate = backDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.backuser_id
     *
     * @return the value of borrow_record.backuser_id
     *
     * @mbg.generated
     */
    public Integer getBackuserId() {
        return backuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.backuser_id
     *
     * @param backuserId the value for borrow_record.backuser_id
     *
     * @mbg.generated
     */
    public void setBackuserId(Integer backuserId) {
        this.backuserId = backuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.actual_back_date
     *
     * @return the value of borrow_record.actual_back_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    public Date getActualBackDate() {
        return actualBackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.actual_back_date
     *
     * @param actualBackDate the value for borrow_record.actual_back_date
     *
     * @mbg.generated
     */
    public void setActualBackDate(Date actualBackDate) {
        this.actualBackDate = actualBackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.status
     *
     * @return the value of borrow_record.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.status
     *
     * @param status the value for borrow_record.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.whether_ext
     *
     * @return the value of borrow_record.whether_ext
     *
     * @mbg.generated
     */
    public String getWhetherExt() {
        return whetherExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.whether_ext
     *
     * @param whetherExt the value for borrow_record.whether_ext
     *
     * @mbg.generated
     */
    public void setWhetherExt(String whetherExt) {
        this.whetherExt = whetherExt == null ? null : whetherExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.prev_borrow_id
     *
     * @return the value of borrow_record.prev_borrow_id
     *
     * @mbg.generated
     */
    public Integer getPrevBorrowId() {
        return prevBorrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.prev_borrow_id
     *
     * @param prevBorrowId the value for borrow_record.prev_borrow_id
     *
     * @mbg.generated
     */
    public void setPrevBorrowId(Integer prevBorrowId) {
        this.prevBorrowId = prevBorrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_record.ext_date
     *
     * @return the value of borrow_record.ext_date
     *
     * @mbg.generated
     */
    public Date getExtDate() {
        return extDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_record.ext_date
     *
     * @param extDate the value for borrow_record.ext_date
     *
     * @mbg.generated
     */
    public void setExtDate(Date extDate) {
        this.extDate = extDate;
    }
}