package com.worldpara.domain;

public class LibraryRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column library_record.library
     *
     * @mbg.generated
     */
    private Integer library;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column library_record.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column library_record.library
     *
     * @return the value of library_record.library
     *
     * @mbg.generated
     */
    public Integer getLibrary() {
        return library;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column library_record.library
     *
     * @param library the value for library_record.library
     *
     * @mbg.generated
     */
    public void setLibrary(Integer library) {
        this.library = library;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column library_record.location
     *
     * @return the value of library_record.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column library_record.location
     *
     * @param location the value for library_record.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}