package com.worldpara.domain;

public class PenaltyRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penalty_record.penalty_record
     *
     * @mbg.generated
     */
    private Integer penaltyRecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penalty_record.borrow_id
     *
     * @mbg.generated
     */
    private Integer borrowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penalty_record.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penalty_record.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penalty_record.penalty_type
     *
     * @mbg.generated
     */
    private String penaltyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penalty_record.penalty
     *
     * @mbg.generated
     */
    private Double penalty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penalty_record.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penalty_record.penalty_record
     *
     * @return the value of penalty_record.penalty_record
     *
     * @mbg.generated
     */
    public Integer getPenaltyRecord() {
        return penaltyRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penalty_record.penalty_record
     *
     * @param penaltyRecord the value for penalty_record.penalty_record
     *
     * @mbg.generated
     */
    public void setPenaltyRecord(Integer penaltyRecord) {
        this.penaltyRecord = penaltyRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penalty_record.borrow_id
     *
     * @return the value of penalty_record.borrow_id
     *
     * @mbg.generated
     */
    public Integer getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penalty_record.borrow_id
     *
     * @param borrowId the value for penalty_record.borrow_id
     *
     * @mbg.generated
     */
    public void setBorrowId(Integer borrowId) {
        this.borrowId = borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penalty_record.user_id
     *
     * @return the value of penalty_record.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penalty_record.user_id
     *
     * @param userId the value for penalty_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penalty_record.admin_id
     *
     * @return the value of penalty_record.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penalty_record.admin_id
     *
     * @param adminId the value for penalty_record.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penalty_record.penalty_type
     *
     * @return the value of penalty_record.penalty_type
     *
     * @mbg.generated
     */
    public String getPenaltyType() {
        return penaltyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penalty_record.penalty_type
     *
     * @param penaltyType the value for penalty_record.penalty_type
     *
     * @mbg.generated
     */
    public void setPenaltyType(String penaltyType) {
        this.penaltyType = penaltyType == null ? null : penaltyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penalty_record.penalty
     *
     * @return the value of penalty_record.penalty
     *
     * @mbg.generated
     */
    public Double getPenalty() {
        return penalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penalty_record.penalty
     *
     * @param penalty the value for penalty_record.penalty
     *
     * @mbg.generated
     */
    public void setPenalty(Double penalty) {
        this.penalty = penalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penalty_record.status
     *
     * @return the value of penalty_record.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penalty_record.status
     *
     * @param status the value for penalty_record.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}