package com.worldpara.domain;

public class Reader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.reader_id
     *
     * @mbg.generated
     */
    private Integer readerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.id_card_number
     *
     * @mbg.generated
     */
    private Integer idCardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.deposit
     *
     * @mbg.generated
     */
    private Double deposit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.reader_id
     *
     * @return the value of reader.reader_id
     *
     * @mbg.generated
     */
    public Integer getReaderId() {
        return readerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.reader_id
     *
     * @param readerId the value for reader.reader_id
     *
     * @mbg.generated
     */
    public void setReaderId(Integer readerId) {
        this.readerId = readerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.id_card_number
     *
     * @return the value of reader.id_card_number
     *
     * @mbg.generated
     */
    public Integer getIdCardNumber() {
        return idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.id_card_number
     *
     * @param idCardNumber the value for reader.id_card_number
     *
     * @mbg.generated
     */
    public void setIdCardNumber(Integer idCardNumber) {
        this.idCardNumber = idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.deposit
     *
     * @return the value of reader.deposit
     *
     * @mbg.generated
     */
    public Double getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.deposit
     *
     * @param deposit the value for reader.deposit
     *
     * @mbg.generated
     */
    public void setDeposit(Double deposit) {
        this.deposit = deposit;
    }
}