package com.worldpara.domain;

public class Resources {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.resources_id
     *
     * @mbg.generated
     */
    private Integer resourcesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.resources_sum
     *
     * @mbg.generated
     */
    private String resourcesSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.resources_id
     *
     * @return the value of resources.resources_id
     *
     * @mbg.generated
     */
    public Integer getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.resources_id
     *
     * @param resourcesId the value for resources.resources_id
     *
     * @mbg.generated
     */
    public void setResourcesId(Integer resourcesId) {
        this.resourcesId = resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.resources_sum
     *
     * @return the value of resources.resources_sum
     *
     * @mbg.generated
     */
    public String getResourcesSum() {
        return resourcesSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.resources_sum
     *
     * @param resourcesSum the value for resources.resources_sum
     *
     * @mbg.generated
     */
    public void setResourcesSum(String resourcesSum) {
        this.resourcesSum = resourcesSum == null ? null : resourcesSum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.url
     *
     * @return the value of resources.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.url
     *
     * @param url the value for resources.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.type
     *
     * @return the value of resources.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.type
     *
     * @param type the value for resources.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.status
     *
     * @return the value of resources.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.status
     *
     * @param status the value for resources.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.method
     *
     * @return the value of resources.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.method
     *
     * @param method the value for resources.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }
}