package com.worldpara.domain;

public class ResourcesRoleRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_R_relation.R_to_R_id
     *
     * @mbg.generated
     */
    private Integer rToRId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_R_relation.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_R_relation.resources_id
     *
     * @mbg.generated
     */
    private Integer resourcesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_R_relation.R_to_R_id
     *
     * @return the value of R_R_relation.R_to_R_id
     *
     * @mbg.generated
     */
    public Integer getrToRId() {
        return rToRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_R_relation.R_to_R_id
     *
     * @param rToRId the value for R_R_relation.R_to_R_id
     *
     * @mbg.generated
     */
    public void setrToRId(Integer rToRId) {
        this.rToRId = rToRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_R_relation.role_id
     *
     * @return the value of R_R_relation.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_R_relation.role_id
     *
     * @param roleId the value for R_R_relation.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_R_relation.resources_id
     *
     * @return the value of R_R_relation.resources_id
     *
     * @mbg.generated
     */
    public Integer getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_R_relation.resources_id
     *
     * @param resourcesId the value for R_R_relation.resources_id
     *
     * @mbg.generated
     */
    public void setResourcesId(Integer resourcesId) {
        this.resourcesId = resourcesId;
    }
}