package com.worldpara.domain;

public class RoleUserRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user_record.relation_id
     *
     * @mbg.generated
     */
    private Integer relationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user_record.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user_record.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user_record.relation_id
     *
     * @return the value of role_user_record.relation_id
     *
     * @mbg.generated
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user_record.relation_id
     *
     * @param relationId the value for role_user_record.relation_id
     *
     * @mbg.generated
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user_record.role_id
     *
     * @return the value of role_user_record.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user_record.role_id
     *
     * @param roleId the value for role_user_record.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user_record.user_id
     *
     * @return the value of role_user_record.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user_record.user_id
     *
     * @param userId the value for role_user_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}