package com.worldpara.domain;

public class RuleRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_record.rule_id
     *
     * @mbg.generated
     */
    private Integer ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_record.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_record.ext_times
     *
     * @mbg.generated
     */
    private Integer extTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_record.overdue_days
     *
     * @mbg.generated
     */
    private Integer overdueDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_record.borrow_value_limited
     *
     * @mbg.generated
     */
    private Integer borrowValueLimited;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_record.rule_id
     *
     * @return the value of rule_record.rule_id
     *
     * @mbg.generated
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_record.rule_id
     *
     * @param ruleId the value for rule_record.rule_id
     *
     * @mbg.generated
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_record.status
     *
     * @return the value of rule_record.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_record.status
     *
     * @param status the value for rule_record.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_record.ext_times
     *
     * @return the value of rule_record.ext_times
     *
     * @mbg.generated
     */
    public Integer getExtTimes() {
        return extTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_record.ext_times
     *
     * @param extTimes the value for rule_record.ext_times
     *
     * @mbg.generated
     */
    public void setExtTimes(Integer extTimes) {
        this.extTimes = extTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_record.overdue_days
     *
     * @return the value of rule_record.overdue_days
     *
     * @mbg.generated
     */
    public Integer getOverdueDays() {
        return overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_record.overdue_days
     *
     * @param overdueDays the value for rule_record.overdue_days
     *
     * @mbg.generated
     */
    public void setOverdueDays(Integer overdueDays) {
        this.overdueDays = overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_record.borrow_value_limited
     *
     * @return the value of rule_record.borrow_value_limited
     *
     * @mbg.generated
     */
    public Integer getBorrowValueLimited() {
        return borrowValueLimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_record.borrow_value_limited
     *
     * @param borrowValueLimited the value for rule_record.borrow_value_limited
     *
     * @mbg.generated
     */
    public void setBorrowValueLimited(Integer borrowValueLimited) {
        this.borrowValueLimited = borrowValueLimited;
    }
}