package com.worldpara.domain;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class User {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.user_id
	 *
	 * @mbg.generated
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.username
	 *
	 * @mbg.generated
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.password
	 *
	 * @mbg.generated
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.email
	 *
	 * @mbg.generated
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.reg_date
	 *
	 * @mbg.generated
	 */
	private Date regDate;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.status
	 *
	 * @mbg.generated
	 */
	private String status;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.gender
	 *
	 * @mbg.generated
	 */
	private String gender;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.tel
	 *
	 * @mbg.generated
	 */
	private String tel;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.icon
	 *
	 * @mbg.generated
	 */
	private String icon;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.last_login_time
	 *
	 * @mbg.generated
	 */
	private Date lastLoginTime;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.user_id
	 *
	 * @return the value of user.user_id
	 * @mbg.generated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.user_id
	 *
	 * @param userId the value for user.user_id
	 * @mbg.generated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.username
	 *
	 * @return the value of user.username
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.username
	 *
	 * @param username the value for user.username
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.password
	 *
	 * @return the value of user.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.password
	 *
	 * @param password the value for user.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.email
	 *
	 * @return the value of user.email
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.email
	 *
	 * @param email the value for user.email
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.reg_date
	 *
	 * @return the value of user.reg_date
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.reg_date
	 *
	 * @param regDate the value for user.reg_date
	 * @mbg.generated
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.status
	 *
	 * @return the value of user.status
	 * @mbg.generated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.status
	 *
	 * @param status the value for user.status
	 * @mbg.generated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.gender
	 *
	 * @return the value of user.gender
	 * @mbg.generated
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.gender
	 *
	 * @param gender the value for user.gender
	 * @mbg.generated
	 */
	public void setGender(String gender) {
		this.gender = gender == null ? null : gender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.tel
	 *
	 * @return the value of user.tel
	 * @mbg.generated
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.tel
	 *
	 * @param tel the value for user.tel
	 * @mbg.generated
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.icon
	 *
	 * @return the value of user.icon
	 * @mbg.generated
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.icon
	 *
	 * @param icon the value for user.icon
	 * @mbg.generated
	 */
	public void setIcon(String icon) {
		this.icon = icon == null ? null : icon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.last_login_time
	 *
	 * @return the value of user.last_login_time
	 * @mbg.generated
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.last_login_time
	 *
	 * @param lastLoginTime the value for user.last_login_time
	 * @mbg.generated
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}
}