package com.worldpara.mapper.inf;

import com.worldpara.domain.BookInformation;
import com.worldpara.domain.BookInformationExample;

import java.util.List;

public interface BookInformationMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table book_infofmation
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer bookId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table book_infofmation
	 *
	 * @mbg.generated
	 */
	int insert(BookInformation record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table book_infofmation
	 *
	 * @mbg.generated
	 */
	int insertSelective(BookInformation record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table book_infofmation
	 *
	 * @mbg.generated
	 */
	List<BookInformation> selectByExample(BookInformationExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table book_infofmation
	 *
	 * @mbg.generated
	 */
	BookInformation selectByPrimaryKey(Integer bookId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table book_infofmation
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(BookInformation record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table book_infofmation
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(BookInformation record);

	List<BookInformation> selectByBookname(String bookName);

	List<BookInformation> selectByISBN(String isbn);

	List<BookInformation> likeByBookname(String bookName);

}