package com.worldpara.mapper.inf;

import com.worldpara.domain.BookInformation;
import com.worldpara.domain.BookInventory;
import com.worldpara.domain.BookInventoryExample;
import java.util.List;

public interface BookInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_inventory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer bookitemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_inventory
     *
     * @mbg.generated
     */
    int insert(BookInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_inventory
     *
     * @mbg.generated
     */
    int insertSelective(BookInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_inventory
     *
     * @mbg.generated
     */
    List<BookInventory> selectByExample(BookInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_inventory
     *
     * @mbg.generated
     */
    BookInventory selectByPrimaryKey(Integer bookitemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BookInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BookInventory record);

    List<BookInventory> searchByBookID(BookInformation bookInformation);
}