package com.worldpara.mapper.inf;

import com.worldpara.domain.CDInventory;
import com.worldpara.domain.CDInventoryExample;
import java.util.List;

public interface CDInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_inventory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_inventory
     *
     * @mbg.generated
     */
    int insert(CDInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_inventory
     *
     * @mbg.generated
     */
    int insertSelective(CDInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_inventory
     *
     * @mbg.generated
     */
    List<CDInventory> selectByExample(CDInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_inventory
     *
     * @mbg.generated
     */
    CDInventory selectByPrimaryKey(Integer cdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CDInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CDInventory record);
}