package com.worldpara.mapper.inf;

import com.worldpara.domain.LibraryRecord;
import com.worldpara.domain.LibraryRecordExample;
import java.util.List;

public interface LibraryRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer library);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_record
     *
     * @mbg.generated
     */
    int insert(LibraryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_record
     *
     * @mbg.generated
     */
    int insertSelective(LibraryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_record
     *
     * @mbg.generated
     */
    List<LibraryRecord> selectByExample(LibraryRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_record
     *
     * @mbg.generated
     */
    LibraryRecord selectByPrimaryKey(Integer library);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LibraryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table library_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LibraryRecord record);

    List<LibraryRecord> allRecords();
}