package com.worldpara.mapper.inf;

import com.worldpara.domain.OverdueRecord;
import com.worldpara.domain.OverdueRecordExample;

import java.util.List;

public interface OverdueRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer overdueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated
     */
    int insert(OverdueRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated
     */
    int insertSelective(OverdueRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated
     */
    List<OverdueRecord> selectByExample(OverdueRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated
     */
    OverdueRecord selectByPrimaryKey(Integer overdueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OverdueRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OverdueRecord record);

    List<OverdueRecord> searchByUserID(int userID);

    List<OverdueRecord> searchByBorrowID(int borrowID);

    List<OverdueRecord> getcurrentActiveOverdueByUserID(int userID);
}