package com.worldpara.mapper.inf;

import com.worldpara.domain.ResourcesRoleRelation;
import com.worldpara.domain.ResourcesRoleRelationExample;
import java.util.List;

public interface ResourcesRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_R_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rToRId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_R_relation
     *
     * @mbg.generated
     */
    int insert(ResourcesRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_R_relation
     *
     * @mbg.generated
     */
    int insertSelective(ResourcesRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_R_relation
     *
     * @mbg.generated
     */
    List<ResourcesRoleRelation> selectByExample(ResourcesRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_R_relation
     *
     * @mbg.generated
     */
    ResourcesRoleRelation selectByPrimaryKey(Integer rToRId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_R_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResourcesRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_R_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResourcesRoleRelation record);
}