package com.worldpara.mapper.inf;

import com.worldpara.domain.RuleRecord;
import com.worldpara.domain.RuleRecordExample;
import java.util.List;

public interface RuleRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_record
     *
     * @mbg.generated
     */
    int insert(RuleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_record
     *
     * @mbg.generated
     */
    int insertSelective(RuleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_record
     *
     * @mbg.generated
     */
    List<RuleRecord> selectByExample(RuleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_record
     *
     * @mbg.generated
     */
    RuleRecord selectByPrimaryKey(Integer ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RuleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RuleRecord record);
}